spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/namuwiki
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 100
#      show_sql: true
        format_sql: true
        open-in-view: true
        profiles:
        active: local

  thymeleaf:
    cache: false

  servlet:
    multipart:
      enabled: true
      location: C:\\upload
      max-file-size: 10MB
      max-request-size: 30MB

logging:
  level:
    org.hibernate.SQL: debug
